### ISSUE TITLE
Change from peer-to-peer to client/server communication model.

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#7]

**Comment by jorisvr** [comment]
I think this happens when the server receives multiple connections with identical context name.

This is a fundamental problem in our design. It can occur due to bad client configuration, or running multiple instances of a client, or when the server has a stale lingering connection from a previous client session. In all these cases, the server ends up with multiple connections to identically-named contexts and will not know how to route messages to that context.

I think we should consider changing our messaging logic as follows:
* Client marks outgoing connection as a route to the server context (as it does now)
* Server will not mark incoming connections as route to client context; instead such incoming connections are only used to route replies for requests that arrived through the connection.

I added a check to avoid permanent failure of the server program when this bug is triggered (5e4126b86542911509a557c322c02ad70fee48c6). But the underlying issue remains.

**Comment by jorisvr** [comment]
Done and merged to master 7c2212ad023abbbe088d6cbb6e8213a9f5c6d463.
